strategy realistic = minE (total) [<=2000] {\
Robot.location,Robot.dest,Robot.cur_waypoint,Robot.dest_waypoint,\
Robot.visited[0],\
Robot.visited[1],\
Robot.visited[2],\
Robot.visited[3],\
Robot.visited[4],\
Robot.visited[5],\
Robot.visited[6],\
Robot.visited[7],\
Robot.visited[8],\
Robot.visited[9],\
Robot.visited[10],\
Robot.visited[11],\
Robot.visited[12],\
Robot.visited[13],\
Robot.visited[14],\
Robot.visited[15],\
Robot.visited[16],\
Robot.visited[17],\
Robot.visited[18],\
Robot.visited[19],\
Robot.visited[20],\
Robot.visited[21],\
Robot.visited[22],\
Robot.visited[23],\
Robot.visited[24],\
Robot.visited[25],\
Robot.visited[26],\
Robot.visited[27],\
Robot.visited[28],\
Robot.visited[29],\
Robot.visited[30],\
Robot.visited[31],\
Robot.visited[32],\
Robot.visited[33],\
Robot.visited[34],\
Robot.visited[35],\
Robot.visited[36],\
Robot.visited[37],\
Robot.visited[38],\
Robot.visited[39],\
Robot.visited[40],\
Robot.visited[41],\
Robot.visited[42],\
Robot.visited[43],\
Robot.visited[44],\
Robot.visited[45],\
Robot.visited[46],\
Robot.visited[47],\
Robot.visited[48],\
Robot.visited[49],\
Robot.visited[50],\
Robot.visited[51],\
Robot.visited[52],\
Robot.visited[53],\
Robot.visited[54],\
Robot.visited[55],\
Robot.visited[56],\
Robot.visited[57],\
Robot.visited[58],\
Robot.visited[59],\
Robot.visited[60],\
Robot.visited[61],\
Robot.visited[62],\
Robot.visited[63],\
Robot.visited[64],\
Robot.visited[65],\
Robot.visited[66],\
Robot.visited[67],\
Robot.visited[68],\
Robot.visited[69],\
Robot.visited[70],\
Robot.visited[71],\
Robot.visited[72],\
Robot.visited[73],\
Robot.visited[74],\
Robot.visited[75],\
Robot.visited[76],\
Robot.visited[77],\
Robot.visited[78],\
Robot.visited[79],\
Robot.visited[80],\
Robot.visited[81],\
Robot.visited[82],\
Robot.visited[83],\
Robot.visited[84],\
Robot.visited[85],\
Robot.visited[86],\
Robot.visited[87],\
Robot.visited[88],\
Robot.visited[89],\
Robot.visited[90],\
Robot.visited[91],\
Robot.visited[92],\
Robot.visited[93],\
Robot.visited[94],\
Robot.visited[95],\
Robot.visited[96],\
Robot.visited[97],\
Robot.visited[98],\
Robot.visited[99],\
Robot.visited[100],\
Robot.visited[101],\
Robot.dest, Robot.cur_waypoint, Robot.dest_waypoint } -> {\
Waypoint(0).num_in_queue,\
Waypoint(1).num_in_queue,\
Waypoint(2).num_in_queue,\
Waypoint(3).num_in_queue,\
Waypoint(4).num_in_queue,\
Waypoint(5).num_in_queue,\
Waypoint(6).num_in_queue,\
Waypoint(7).num_in_queue,\
Waypoint(8).num_in_queue,\
Waypoint(9).num_in_queue,\
Waypoint(10).num_in_queue,\
Waypoint(11).num_in_queue,\
Waypoint(12).num_in_queue,\
Waypoint(13).num_in_queue,\
Waypoint(14).num_in_queue,\
Waypoint(15).num_in_queue,\
Waypoint(16).num_in_queue,\
Waypoint(17).num_in_queue,\
Waypoint(18).num_in_queue,\
Waypoint(19).num_in_queue,\
Waypoint(20).num_in_queue,\
Waypoint(21).num_in_queue,\
Waypoint(22).num_in_queue,\
Waypoint(23).num_in_queue,\
Waypoint(24).num_in_queue,\
Waypoint(25).num_in_queue,\
Waypoint(26).num_in_queue,\
Waypoint(27).num_in_queue,\
Waypoint(28).num_in_queue,\
Waypoint(29).num_in_queue,\
Waypoint(30).num_in_queue,\
Waypoint(31).num_in_queue,\
Waypoint(32).num_in_queue,\
Waypoint(33).num_in_queue,\
Waypoint(34).num_in_queue,\
Waypoint(35).num_in_queue,\
Waypoint(36).num_in_queue,\
Waypoint(37).num_in_queue,\
Waypoint(38).num_in_queue,\
Waypoint(39).num_in_queue,\
Waypoint(40).num_in_queue,\
Waypoint(41).num_in_queue,\
Waypoint(42).num_in_queue,\
Waypoint(43).num_in_queue,\
Waypoint(44).num_in_queue,\
Waypoint(45).num_in_queue,\
Waypoint(46).num_in_queue,\
Waypoint(47).num_in_queue,\
Waypoint(48).num_in_queue,\
Waypoint(49).num_in_queue,\
Waypoint(50).num_in_queue,\
Waypoint(51).num_in_queue,\
Waypoint(52).num_in_queue,\
Waypoint(53).num_in_queue,\
Waypoint(54).num_in_queue,\
Waypoint(55).num_in_queue,\
Waypoint(56).num_in_queue,\
Waypoint(57).num_in_queue,\
Waypoint(58).num_in_queue,\
Waypoint(59).num_in_queue,\
Waypoint(60).num_in_queue,\
Waypoint(61).num_in_queue,\
Waypoint(62).num_in_queue,\
Waypoint(63).num_in_queue,\
Waypoint(64).num_in_queue,\
Waypoint(65).num_in_queue,\
Waypoint(66).num_in_queue,\
Waypoint(67).num_in_queue,\
Waypoint(68).num_in_queue,\
Waypoint(69).num_in_queue,\
Waypoint(70).num_in_queue,\
Waypoint(71).num_in_queue,\
Waypoint(72).num_in_queue,\
Waypoint(73).num_in_queue,\
Waypoint(74).num_in_queue,\
Waypoint(75).num_in_queue,\
Waypoint(76).num_in_queue,\
Waypoint(77).num_in_queue,\
Waypoint(78).num_in_queue,\
Waypoint(79).num_in_queue,\
Waypoint(80).num_in_queue,\
Waypoint(81).num_in_queue,\
Waypoint(82).num_in_queue,\
Waypoint(83).num_in_queue,\
Waypoint(84).num_in_queue,\
Waypoint(85).num_in_queue,\
Waypoint(86).num_in_queue,\
Waypoint(87).num_in_queue,\
Waypoint(88).num_in_queue,\
Waypoint(89).num_in_queue,\
Waypoint(90).num_in_queue,\
Waypoint(91).num_in_queue,\
Waypoint(92).num_in_queue,\
Waypoint(93).num_in_queue,\
Waypoint(94).num_in_queue,\
Waypoint(95).num_in_queue,\
Waypoint(96).num_in_queue,\
Waypoint(97).num_in_queue,\
Waypoint(98).num_in_queue,\
Waypoint(99).num_in_queue,\
Waypoint(100).num_in_queue,\
Waypoint(101).num_in_queue,\
	Robot.x} : <> Robot.Done
simulate 1 [<= 2000] {Robot.Holding, Robot.cur_waypoint, Robot.dest_waypoint} under realistic
saveStrategy("waypoint_strategy.json", realistic)
