#ifndef GLOBALS_HPP
#define GLOBALS_HPP

#define TIME_AT_VERTEX 50
#define DESYNC_BUFFER 75
#define DELTA 1
#define TIME_AT_GOAL 300

#define SWAP_CONFLICT_PENALTY 500
#define VERTEX_CONFLICT_PENALTY 50
#define FOLLOW_CONFLICT_PENALTY 5

#endif